version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:06"
    timezone: "UTC"


  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:06"
    timezone: "UTC"